name: iOS 构建工作流

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: 构建未签名IPA文件
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      
      - name: 构建未签名IPA
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then 
            filetype_parameter="workspace" 
            file_to_build="`ls -A | grep -i \\.xcworkspace\$`"
          else 
            filetype_parameter="project" 
            file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          
          # 创建构建目录
          mkdir -p build
          
          # 构建应用程序
          xcodebuild -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -configuration Release -archivePath ./build/app.xcarchive archive
          
          # 创建导出选项
          cat << EOF > ./build/options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>manual</string>
          </dict>
          </plist>
          EOF
          
          # 导出未签名IPA
          xcodebuild -exportArchive -archivePath ./build/app.xcarchive -exportPath ./build/output -exportOptionsPlist ./build/options.plist
      
      - name: 上传IPA构建产物
        uses: actions/upload-artifact@v3
        with:
          name: app-unsigned
          path: ./build/output
          # retention-days: 5