name: iOS 构建工作流

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: 构建未签名IPA文件
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      
      - name: 构建应用
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then 
            filetype_parameter="workspace" 
            file_to_build="`ls -A | grep -i \\.xcworkspace\$`"
          else 
            filetype_parameter="project" 
            file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          
          # 创建构建目录
          mkdir -p build/Payload
          
          # 直接构建应用程序到指定路径，跳过签名
          xcodebuild -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -configuration Release CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" EXPANDED_CODE_SIGN_IDENTITY="" -sdk iphoneos -derivedDataPath ./build
          
          # 查找并复制.app文件到Payload目录
          find ./build -name "*.app" -type d -exec cp -R {} ./build/Payload/ \;
          
          # 创建IPA文件
          cd ./build
          zip -r app-unsigned.ipa Payload
          cd ..
      
      - name: 上传IPA构建产物
        uses: actions/upload-artifact@v4
        with:
          name: app-unsigned
          path: ./build/app-unsigned.ipa
          retention-days: 5